### PR TITLE
fix: Cancel zero address as the default from address

### LINKED ISSUE #1067: [BUG] graph-node error: `Possible reorg detected`
## **Version**
- Godwoken v1 mainnet

## **Describe the bug**

graph-node pointing to `https://v1.mainnet.godwoken.io/rpc`

```console
Done processing trigger, gas_used: 0, data_source: ERC721, handler: handleTransfer, total_ms: 3169, transaction: 0x1d56…229d, address: 0x2012…95a8, signature: Transfer(indexed address,indexed address,indexed uint256), sgd: 1, subgraph_id: QmQRtVCkr62VV7GqgqdUcAdhoeRy81UfaFcSm1DnBR7Mmv, component: SubgraphInstanceManager
Possible reorg detected, retrying, error: failed to process trigger: block #17463 (0x589c…6d84), transaction 1d567f5bd234f984b9a9651399346c279bd72fc22ac919e19c69a0e005a5229d: Ethereum node returned an error when calling function "supportsInterface" of contract "INationNFT": RPC error: Error { code: InvalidRequest, message: "check balance err: Can't find address for sender: 11377", data: None }
wasm backtrace:
    0: 0x28e7 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall
    1: 0x2a0b - <unknown>!src/types/ERC721/INationNFT/INationNFT#try_supportsInterface
    2: 0x3c84 - <unknown>!src/mappings/utils/ERC721/getOrCreateCollection
    3: 0x48fb - <unknown>!src/mappings/ERC721/handleTransfer
, block_hash: 0x589c39e28f7b8dbdf652f13b59cec2d73d3632ec0c393afe726ee714d5c76d84, block_number: 17463, sgd: 1, subgraph_id: QmQRtVCkr62VV7GqgqdUcAdhoeRy81UfaFcSm1DnBR7Mmv, component: SubgraphInstanceManager
```

### PR DESCRIPTION
**Pull request by classicalliu**
Related:
- https://github.com/godwokenrises/godwoken/issues/1067

zero address deposited in godwoken block 372398, so when `eth_call` requires execute before this block and use zero address as default from will failed

So using first EOA account as default from address will resolve the problem

### CODE REVIEW

File: web3/packages/api-server/src/base/gw-config.ts [hunk 1]
```diff
@@ -437,7 +432,7 @@ function toApiNodeInfo(nodeInfo: GwNodeInfo): NodeInfo {
   return snakeToCamel(nodeInfo, ["code_hash", "hash_type"]);
 }
 
-async function zeroAddressAccount(
+async function _zeroAddressAccount(
```
Comment (jjyr) [inline web3/packages/api-server/src/base/gw-config.ts]: Please delete this function.

Comment (classicalliu) [reply web3/packages/api-server/src/base/gw-config.ts]: Updated

File: web3/packages/api-server/src/base/gw-config.ts [hunk 2]
```diff
@@ -237,11 +236,6 @@ export class GwConfig {
   private async fetchDefaultFromAccount(
```
Comment (Flouse) [inline web3/packages/api-server/src/base/gw-config.ts:235]: This comment `// Using zero address firstly` could be deleted?

**Review by Flouse — DISMISSED** [review]

File: web3/packages/api-server/src/base/gw-config.ts (hunk 2 above)
Comment (classicalliu) [reply web3/packages/api-server/src/base/gw-config.ts:235]: Updated

**Review by jjyr — APPROVED** [review]

**Review by Flouse — APPROVED** [review]
