### PR TITLE
fix: Remove `extra` from RPC error in response

### LINKED ISSUE #1012: [BUG] Graph-node is broken on mainnet due to eth_call response incompatibility
Graph node completely stops working on Godwoken Mainnet as soon as it encounters errors in eth_call. Normally it should be handled by try_call and it was working fine until latest update of Godwoken which introduced "extra" field in eth_call response in case of error.

Godwoken:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "execution reverted",
        "extra": {
            "exit_code": "0x2",
            "message": "revert",
            "stack": "EVMC"
        }
    }
}
```

Goerli:
```
{
    "jsonrpc": "2.0",
    "id": 48,
    "error": {
        "code": -32000,
        "message": "execution reverted"
    }
}
```

---

Example request that triggers revert:

```
curl --location 'https://v1.mainnet.godwoken.io/rpc' \
--header 'Content-Type: application/json' \
--data '{
    "method": "eth_call",
    "params": [
        {
            "gas": "0xb71b00",
            "from": "0x9c023610d438dE45B8D53358DE663233Ce752F77",
            "to": "0x186181e225dc1ad85a4a94164232bd261e351c33",
            "data": "0x38fff2d0"
        },
        "0x3c3b5"
    ],
    "jsonrpc": "2.0",
    "id": 1
}'
```

Response:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "execution reverted",
        "extra": {
            "exit_code": "0x2",
            "message": "revert",
            "stack": "EVMC"
        }
    }
}
```

Graph errors:
```
docker-graph-node-1  | Mar 02 15:50:21.239 INFO Done processing trigger, gas_used: 0, data_source: WeightedPoolFactory, handler: handleWeightedPoolCreated, total_ms: 3106, transaction: 0x2112…41ec, address: 0x8a55…5202, signature: PoolCreated(indexed address), sgd: 1, subgraph_id: QmduxKxtMxya25Us5a5ZFYJKKpxnCSkyNDLm9A6EKANzuR, component: SubgraphInstanceManager
docker-graph-node-1  | Mar 02 15:50:21.239 INFO Possible reorg detected, retrying, error: failed to process trigger: block #246709 (0x879b…73f5), transaction 21128e6dd687f6016206390a52204e4bf45f4d4a376622ed15442676243241ec: Ethereum node returned an error when calling function "getPoolId" of contract "WeightedPool": failed to deserialize response: data did not match any variant of untagged enum Output
docker-graph-node-1  | wasm backtrace:
docker-graph-node-1  |     0: 0x1e0c - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#tryCall
docker-graph-node-1  |     1: 0x4157 - <unknown>!src/mappings/balancer/helpers/misc/createToken
docker-graph-node-1  |     2: 0x4683 - <unknown>!src/mappings/balancer/helpers/misc/createPoolTokenEntity
docker-graph-node-1  |     3: 0x506b - <unknown>!src/mappings/balancer/WeightedPool/factory/PoolCreated/createWeightedLikePool
docker-graph-node-1  |     4: 0x508f - <unknown>!src/mappings/balancer/WeightedPool/factory/PoolCreated/handleWeightedPoolCreated
```

I tried using version of graph-node: 0.25, 0.27, 0.29, 0.30. All broken.

### PR DESCRIPTION
**Pull request by Flouse**
- cherry-pick from https://github.com/godwokenrises/godwoken/pull/1013
- resolve https://github.com/godwokenrises/godwoken/issues/1012

### CODE REVIEW

File: web3/packages/api-server/src/methods/index.ts [hunk 1]
```diff
@@ -57,9 +57,9 @@ function getMethods(argsList: ModConstructorArgs = {}) {
                 error.data = err.data;
               }
 
-              if (err.extra) {
-                error.extra = err.extra;
-              }
+              // if (err.extra) {
```
Comment (Flouse) [inline web3/packages/api-server/src/methods/index.ts:61]:
```suggestion
              // hotfix https://github.com/godwokenrises/godwoken/issues/1012
              // if (err.extra) {
```

**Review by classicalliu — APPROVED** [review]

**Review by zeroqn — APPROVED** [review]
