### PR TITLE
fix: ChainTask: retry on RPC request error

### LINKED ISSUE #676: Godwoken v1 node exits after losing connection with CKB node.
The Godwoken v1 node exits every time it loses connection with the CKB node. This seems like it may be undesired functionality since the node will exit instead of recovering if there is a temporary connectivity issue with the node.

```
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.603141Z ERROR gw_block_producer::runner: chain polling loop exit unexpected, error: ckb client error, method: get_block_by_number error: error sending request for url (http://192.168.0.73:18114/): error trying to connect: tcp connect error: Connection refused (os error 111)
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.606026Z  INFO gw_block_producer::runner: send shutdown event
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.606080Z  INFO gw_rpc_server::server: rpc server exited successfully
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.606469Z  INFO gw_rpc_ws_server::server: ws server exited successfully
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.606730Z ERROR gw_rpc_server::registry: rpc submit tx is closed
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.608287Z  INFO gw_block_producer::runner: Exiting...
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.608379Z  INFO gw_rpc_ws_server::notify_controller: [error tx receipt] notify service stop
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.608390Z ERROR gw_rpc_ws_server::subscription: [error tx receipt] notify service stop receiving from an empty and closed channel
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.608766Z  INFO gw_mem_pool::pool: Saving mem block to "/mnt/mem-pool/mem-block"
gw-testnet_v1-readonly    | 2022-04-26T05:22:33.608983Z  INFO gw_mem_pool::restore_manager: [mem-pool] save restore save mem block "/mnt/mem-pool/mem-block/mem_block_timestamp_1650950553608"
gw-testnet_v1-readonly exited with code 0
```

### PR DESCRIPTION
**Pull request by blckngm**
Added a exponential backoff utility, with full random jitter support.

The p2p network re-connect is also changed to use this backoff utility.

Manually tested with stopping and restarting ckb/ckb-indexer in kicker. Close #676.

### CODE REVIEW

File: crates/block-producer/src/runner.rs [hunk 1]
```diff
@@ -919,15 +923,22 @@ pub async fn run(config: Config, skip_config_check: bool) -> Result<()> {
...
                         Duration::from_secs(3),
                         ctx,
                         shutdown_send,
                         shutdown_event_recv,
                     );
-                    if let Err(err) = chain_task.run().await {
-                        log::error!("chain polling loop exit unexpected, error: {}", err);
+                    while let Err(err) = chain_task.run(&mut backoff).await {
+                        if err.is::<RPCRequestError>() {
+                            log::error!("chain polling loop request error, will retry: {}", err);
```
Comment (zeroqn) [inline crates/block-producer/src/runner.rs:936]: Suggest log sleep duration

Comment (zeroqn) [inline crates/block-producer/src/runner.rs:936]: Suggest log sleep duration

**Review by zeroqn — APPROVED** [review]

**Review by jjyr — APPROVED** [review]
